# Generated by Django 5.2.14 on 2026-05-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_orderitem_image_alter_order_shippingprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='postalCode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
